INSERT INTO relationship VALUES (1,'Aquarion','rachel walmsley','AFPhiance','AFPhiancee',2);
INSERT INTO relationship VALUES (100,'dragonprince','lonecat','afpfiancee.','afpfiance',0);
INSERT INTO relationship VALUES (101,'Joy','Peter','afpdaughter','afpfather',2);
INSERT INTO relationship VALUES (102,'Joy','Peter','afpkickerinnateef','afpkickeeinnateef',2);
INSERT INTO relationship VALUES (103,'Joy','Melodysk','afpon the same wavelength','afpon the same wavelength',2);
INSERT INTO relationship VALUES (104,'Peter','Martin','afpfiancé','afpfiancé',2);
INSERT INTO relationship VALUES (105,'lonecat','Aquarion','adoptee','adopter',2);
INSERT INTO relationship VALUES (106,'dragonprince','Ali W','afpfiance','affphiancee',0);
INSERT INTO relationship VALUES (107,'dragonprince','Chrissy','afpfiance','affphiancee',2);
INSERT INTO relationship VALUES (108,'dragonprince','Chrissy','afpfiance','afphiancee',0);
INSERT INTO relationship VALUES (109,'dragonprince','nattie','afpfiance','afphiancee',2);
INSERT INTO relationship VALUES (110,'Jens Ayton','Laurabelle','afpfiance','afpfiancee',2);
INSERT INTO relationship VALUES (111,'Melodysk','Thomas P','Willing Victim','AFPvamp',2);
INSERT INTO relationship VALUES (112,'Melodysk','nattie','Lunatic Fringe Member','Lunatic Fringe Member',2);
INSERT INTO relationship VALUES (113,'nattie','Aquarion','Supplemental Sibling','Supplemental Sibling',2);
INSERT INTO relationship VALUES (114,'dragonprince','Bluebottle','brother','sister',0);
INSERT INTO relationship VALUES (115,'dragonprince','rruthi','brother','sister',2);
INSERT INTO relationship VALUES (116,'JennyRad','mmessall','Afpfont','Afprecipient-of-fontishness',2);
INSERT INTO relationship VALUES (117,'Laurabelle','mmessall','AFPDivine Advocate','AFPDevil\'s Advocate',2);
INSERT INTO relationship VALUES (118,'caomhin','Laurabelle','AFPartiality','AFPartial',2);
INSERT INTO relationship VALUES (119,'dragonprince','Ali W','afpiance','afpiance',0);
INSERT INTO relationship VALUES (120,'dragonprince','Ali W','afpfiance','afpiance',0);
INSERT INTO relationship VALUES (121,'mist','Rhys Smith','mr mist','mr rhys',2);
INSERT INTO relationship VALUES (122,'mist','rruthi','fluff slave','fluff daddy',0);
INSERT INTO relationship VALUES (123,'dragonprince','Ali W','afphiance','afphiance',0);
INSERT INTO relationship VALUES (124,'dragonprince','Ali W','afphiance','afphiance',0);
INSERT INTO relationship VALUES (125,'Ali W','dragonprince','#afpiancee','#afpiance',2);
INSERT INTO relationship VALUES (126,'dragonprince','Ali W','afphiance','afphiance',0);
INSERT INTO relationship VALUES (127,'dragonprince','Rosemary','afphiance','afpfiancee',1);
INSERT INTO relationship VALUES (128,'Jennifer','mmessall','afpsister','afpsister',2);
INSERT INTO relationship VALUES (129,'mmessall','Brucianna','AFPfiancee','AFPfiancee',1);
INSERT INTO relationship VALUES (130,'ingvar','Martin','clone','clone',2);
INSERT INTO relationship VALUES (131,'hippo','MartynC','AFPchauffeured','AFPchauffeur',2);
INSERT INTO relationship VALUES (132,'MartynC','Spooky','co-adulterer','co-adulterer',2);
INSERT INTO relationship VALUES (133,'Andrew Nevill','Spooky','AFPfiance','AFPfiance',2);
INSERT INTO relationship VALUES (134,'Orjan','ingvar','Clone','Clone',2);
INSERT INTO relationship VALUES (135,'Orjan','Martin','Clone','Clone',2);
INSERT INTO relationship VALUES (136,'Petri Holopainen','mmessall','AFPfiance','AFPfiance',1);
INSERT INTO relationship VALUES (137,'Liz','cat','sister (irl)','sister (irl)',2);
INSERT INTO relationship VALUES (138,'Liz','oliver_newman','AFPiancee','AFPiance',2);
INSERT INTO relationship VALUES (139,'Liz','dragonprince','AFPiancee','AFPiance',2);
INSERT INTO relationship VALUES (14,'Bluebottle','Peter','afpfiancée','afpfiancé',2);
INSERT INTO relationship VALUES (140,'Liz','dragonprince','AFPiancee','AFPiance',0);
INSERT INTO relationship VALUES (141,'Liz','Corinne','AFPiance','AFPiance',2);
INSERT INTO relationship VALUES (142,'Aquarion','Liz','AFPhiance','AFPhiancee',2);
INSERT INTO relationship VALUES (143,'Liz','mike','AFPiance','AFPiance',2);
INSERT INTO relationship VALUES (144,'Liz','rachel walmsley','AFPiance','AFPiance',2);
INSERT INTO relationship VALUES (145,'Liz','ratty','AFPiance','AFPiance',2);
INSERT INTO relationship VALUES (146,'Liz','ratty','AFPbig sis','AFPikkle sis',2);
INSERT INTO relationship VALUES (147,'dragonprince','Trina','afphiace','afphiace',2);
INSERT INTO relationship VALUES (148,'dragonprince','naomi','not-#afpfinacee','not-#afpfinacee',0);
INSERT INTO relationship VALUES (149,'naomi','dragonprince','not-#afpfiancee','not-#afpfiance',2);
INSERT INTO relationship VALUES (150,'rruthi','Davon','afphiancee','afphiance',2);
INSERT INTO relationship VALUES (151,'rruthi','Supermouse','afpiancee','afpiancee',2);
INSERT INTO relationship VALUES (152,'Jens Ayton','rruthi','#aftopicer','#aftopicee',2);
INSERT INTO relationship VALUES (153,'Jens Ayton','Liz','#afpjiggleappreciator','#afpjiggler',2);
INSERT INTO relationship VALUES (154,'mole','Suzi','afpson','afpmother',2);
INSERT INTO relationship VALUES (155,'mole','Brucianna','afphiance','afphiancee',1);
INSERT INTO relationship VALUES (156,'mole','Rosemary','afphiance','afphiancee',2);
INSERT INTO relationship VALUES (157,'mole','nattie','afphiance','afphiancee',2);
INSERT INTO relationship VALUES (158,'Liz','amy','AFPiancee','AFPiancee',2);
INSERT INTO relationship VALUES (159,'Liz','Rosemary','AFPiancee','AFPiancee',2);
INSERT INTO relationship VALUES (16,'rachel walmsley','Rhys Smith','AFPsheep','AFPWelshman',2);
INSERT INTO relationship VALUES (160,'Liz','rruthi','AFPiancee','AFPiancee',2);
INSERT INTO relationship VALUES (161,'Liz','Supermouse','AFPiancee','AFPiancee',2);
INSERT INTO relationship VALUES (162,'mole','Peter','afphiance','afphiance',2);
INSERT INTO relationship VALUES (163,'Isuldir','Liz','AFPhiance','AFPhiance',2);
INSERT INTO relationship VALUES (164,'Kelvix','dragonprince','afpiancee','afpiance',2);
INSERT INTO relationship VALUES (165,'Kelvix','Martin','afpiancee','afpiance',2);
INSERT INTO relationship VALUES (166,'Liz','perfdrug','AFPbitontheside','AFPbitontheside',2);
INSERT INTO relationship VALUES (167,'dragonprince','ratty','afpiance','afpiance',2);
INSERT INTO relationship VALUES (168,'Sarah','Liz','afpsis','afpsis',2);
INSERT INTO relationship VALUES (169,'Davon','Carrie Cota','AFPbrother','AFPsister',2);
INSERT INTO relationship VALUES (17,'Rhys Smith','mike','AFPnemesis','AFPnemesis',2);
INSERT INTO relationship VALUES (170,'Carrie Cota','cat','AFPmum','afpdaughter',2);
INSERT INTO relationship VALUES (171,'cat','catmum','daughter (irl)','mum (irl)',2);
INSERT INTO relationship VALUES (172,'catmum','Liz','mum (irl)','daughter (irl)',2);
INSERT INTO relationship VALUES (173,'Davon','cat','afpbrother','afpsister',2);
INSERT INTO relationship VALUES (174,'oliver_newman','cat','AFP er?','AFP erm?',2);
INSERT INTO relationship VALUES (175,'oliver_newman','Davon','afpbug','afpbug',2);
INSERT INTO relationship VALUES (176,'Grymma','dragonprince','afphiancee','afphiance',2);
INSERT INTO relationship VALUES (177,'Suzi','Jacqui','AFPhiance','AFPhiancee',1);
INSERT INTO relationship VALUES (178,'Suzi','Peter','doppleganger','doppleganger',0);
INSERT INTO relationship VALUES (179,'quantum moth','April Goodwin-Smith','afpiance','maid of honour',2);
INSERT INTO relationship VALUES (18,'Peter','Ali W','#afpfiancé','#afpfiancée',2);
INSERT INTO relationship VALUES (180,'quantum moth','Aquarion','evil twin','good twin',2);
INSERT INTO relationship VALUES (181,'quantum moth','Corinne','afpiance','afpiancee',2);
INSERT INTO relationship VALUES (182,'quantum moth','eric','afpiance','afpiance',2);
INSERT INTO relationship VALUES (183,'quantum moth','Liz','afpiance','afpiancee',2);
INSERT INTO relationship VALUES (184,'quantum moth','Melodysk','james','jesse',2);
INSERT INTO relationship VALUES (185,'quantum moth','mmessall','afpiance','afpiancee',2);
INSERT INTO relationship VALUES (186,'quantum moth','nattie','reputation','reputor',1);
INSERT INTO relationship VALUES (187,'quantum moth','Peter','afpiance','afpiance',2);
INSERT INTO relationship VALUES (188,'quantum moth','rachel walmsley','james','meowth',2);
INSERT INTO relationship VALUES (189,'charlotte','Liz','#afpfiancee','#afpfiancee',2);
INSERT INTO relationship VALUES (19,'Bluebottle','Peter','RL fiancée','RL fiancé',2);
INSERT INTO relationship VALUES (190,'charlotte','oliver_newman','*hug*er','*hug*ee',2);
INSERT INTO relationship VALUES (191,'Melodysk','rachel walmsley','Jesse','Meowth',2);
INSERT INTO relationship VALUES (192,'Corinne','Martin','afpiancee','afpiance',2);
INSERT INTO relationship VALUES (193,'quantum moth','mike','calvin','hobbes',2);
INSERT INTO relationship VALUES (194,'Liz','tenticle','AFPiancee (eloped)','AFPiance (eloped)',0);
INSERT INTO relationship VALUES (195,'tenticle','Bluebottle','#AFPdopted son','#AFPdopted mum',2);
INSERT INTO relationship VALUES (196,'Suzi','Peter','alter ego','alter ego',2);
INSERT INTO relationship VALUES (197,'hippo','rruthi','AFPhiance','AFPhiancee',2);
INSERT INTO relationship VALUES (198,'Laurabelle','Tachyon','AFPsister','AFPbrother',2);
INSERT INTO relationship VALUES (199,'Chrissy','Tachyon','AFPhiancee','AFPhiance',2);
INSERT INTO relationship VALUES (200,'Andrea','MartynC','owner of cold ankles','ankle warmer',2);
INSERT INTO relationship VALUES (201,'Eponine','dragonprince','afpfiancee','afpfiance',2);
INSERT INTO relationship VALUES (202,'Eponine','mike','afpfiancee','afpfiance',2);
INSERT INTO relationship VALUES (203,'needle','hippo','friend','friend',2);
INSERT INTO relationship VALUES (204,'needle','Supermouse','person she met once','person she met once',2);
INSERT INTO relationship VALUES (205,'Davon','Rosemary','afpiance','afpiance',2);
INSERT INTO relationship VALUES (206,'Marie','Tachyon','AFPotherRee','AFPotherMark',2);
INSERT INTO relationship VALUES (207,'Liz','tenticle','AFPwife','AFPhusband',2);
INSERT INTO relationship VALUES (208,'pol','rruthi','AFPhiance','AFPhiance',2);
INSERT INTO relationship VALUES (209,'Jens Ayton','rruthi','afpfiance','afpfiancee',2);
INSERT INTO relationship VALUES (210,'JamesGreen','lonecat','AFPfriend','AFPfriend',2);
INSERT INTO relationship VALUES (211,'rruthi','hippo','big sister','little brother',2);
INSERT INTO relationship VALUES (212,'rruthi','pol','Owner','Genie',2);
INSERT INTO relationship VALUES (213,'Bluebottle','rachel walmsley','afpmistress','afpmistress',2);
INSERT INTO relationship VALUES (214,'charlotte','oliver_newman','actualfiancee','actualfiance',1);
INSERT INTO relationship VALUES (215,'rachel walmsley','Trina','afpiancée','afpiancée',2);
INSERT INTO relationship VALUES (216,'Davon','Kimmi','afpiance','afpiance',0);
INSERT INTO relationship VALUES (217,'Kimmi','Davon','AFPhiancee','AFPhiancee',2);
INSERT INTO relationship VALUES (218,'sanity','rruthi','AFPhiance','AFPhiancee',2);
INSERT INTO relationship VALUES (219,'hippo','Kimmi','afpsink','afpsauce',2);
INSERT INTO relationship VALUES (22,'rachel walmsley','amy','AFPsis','AFPsis',2);
INSERT INTO relationship VALUES (220,'Guitar_Huw','Kimmi','AFPhiance','AFPhiancee',2);
INSERT INTO relationship VALUES (221,'Guitar_Huw','Corinne','AFPhiance','AFPhiancee',2);
INSERT INTO relationship VALUES (222,'Guitar_Huw','Sam','AFPbigbrother','AFPlittlesister',2);
INSERT INTO relationship VALUES (223,'Sam','ryo-chan','AFPlittlesister','AFPbigsister',2);
INSERT INTO relationship VALUES (224,'Alex TEH','naomi','Brother','Sister',2);
INSERT INTO relationship VALUES (225,'Andrew Irish','Kimmi','Friend','anchor in sanity',2);
INSERT INTO relationship VALUES (226,'Melodysk','sanity','AFPparent','AFPson',2);
INSERT INTO relationship VALUES (227,'tamara','dragonprince','AFPwife','AFPhusband',2);
INSERT INTO relationship VALUES (228,'tamara','rruthi','other Israeli AFPer','other Israeli AFPer',2);
INSERT INTO relationship VALUES (229,'Adrian Morgan','Nanny Ogg','pi-th afpcousin','afpi-th cousin',1);
INSERT INTO relationship VALUES (23,'Supermouse','hippo','Rodent','attic-keeper',2);
INSERT INTO relationship VALUES (230,'Melodysk','lisa','AFPmum','AFPdaughter',2);
INSERT INTO relationship VALUES (231,'cat','lisa','#afpdaughter','#afpmum',2);
INSERT INTO relationship VALUES (232,'cat','ach','#afpdaughter','#afpdad',2);
INSERT INTO relationship VALUES (233,'lisa','sanity','sister','sister',2);
INSERT INTO relationship VALUES (234,'lisa','amy','#afpiancee','#afpiancee',2);
INSERT INTO relationship VALUES (235,'lonecat','rachel walmsley','twin','twin',2);
INSERT INTO relationship VALUES (236,'tenticle','Liz','waterer','afpidistra',2);
INSERT INTO relationship VALUES (237,'cat','ryo-chan','#afpsister','#afpsister',2);
INSERT INTO relationship VALUES (238,'Jens Ayton','cat','#afpsomething','#afpsomething',2);
INSERT INTO relationship VALUES (239,'JamesGreen','cat','afpsomethingelse','afpsomethingelse',2);
INSERT INTO relationship VALUES (240,'Sam','cat','AFPsisterinunderagesnoggery','AFPsisterinunderagesnoggery',2);
INSERT INTO relationship VALUES (241,'perfdrug','cat','owner','pet',2);
INSERT INTO relationship VALUES (242,'rachel walmsley','Kimmi','afpcorruptress','afpcorruptee',2);
INSERT INTO relationship VALUES (243,'Sam','hikari','AFPstalker','AFPstalkee',2);
INSERT INTO relationship VALUES (244,'hikari','rachel walmsley','AFPAnnoyance','AFPgorgeousness',0);
INSERT INTO relationship VALUES (245,'Sam','lisa','AFPsexyfriend','AFPsexyfriend',2);
INSERT INTO relationship VALUES (246,'Tiggs','Andrea','AFPsis','AFPsis',2);
INSERT INTO relationship VALUES (247,'Tiggs','dragonprince','AFPfiance','AFPfiance',2);
INSERT INTO relationship VALUES (248,'Tiggs','Homicide','AFPiance','AFPiance',2);
INSERT INTO relationship VALUES (249,'Tiggs','Melodysk','AFPsis','AFPsis',0);
INSERT INTO relationship VALUES (25,'hippo','Carrie Cota','AFPhiance','AFPhiancee',2);
INSERT INTO relationship VALUES (250,'Tiggs','mike','AFPsis','AFpbruv',1);
INSERT INTO relationship VALUES (251,'Tiggs','Jen','AFPsis','AFPsis',2);
INSERT INTO relationship VALUES (252,'Tiggs','Olivia Harries','AFPsis','AFPsis',1);
INSERT INTO relationship VALUES (253,'Tiggs','rachel walmsley','AFPsis','AFPsis',0);
INSERT INTO relationship VALUES (254,'Tiggs','ratty','AFPlilbigsis','AFPbiglilsis',0);
INSERT INTO relationship VALUES (255,'Tiggs','Tachyon','AFPfiance','AFPfiance',2);
INSERT INTO relationship VALUES (256,'Tiggs','Trina','afpsis','afpsis',2);
INSERT INTO relationship VALUES (257,'Tiggs','Melodysk','AFPsis','AFPsis',2);
INSERT INTO relationship VALUES (258,'Davon','catmum','afpson','afpmum',1);
INSERT INTO relationship VALUES (259,'tamara','BarryR','AFPTwin Sister','AFPTwin Brother',2);
INSERT INTO relationship VALUES (26,'mike','ratty','AFPiance','AFPiancee',2);
INSERT INTO relationship VALUES (260,'Andrew Irish','cat','afpstep cousin once removed','afpstep cousin once removed',2);
INSERT INTO relationship VALUES (261,'hikari','amy','bunad fitter','torturer with blunt objects',2);
INSERT INTO relationship VALUES (262,'hikari','rachel walmsley','persona non grata','null pointer reference',0);
INSERT INTO relationship VALUES (263,'Andrea','Tiggs','HONEY!!!','SWEETIE!!!',2);
INSERT INTO relationship VALUES (264,'rachel walmsley','JamesGreen','zombie brain-share coparticipant','zombie brain-share coparticipant',2);
INSERT INTO relationship VALUES (265,'rachel walmsley','nattie','agneau','bergere',1);
INSERT INTO relationship VALUES (266,'Homicide','Liz','Other bit on the side','Wonderful and Wanton mistress',2);
INSERT INTO relationship VALUES (267,'cat','Isuldir','AFPhiance','AFPhiance',2);
INSERT INTO relationship VALUES (268,'Davon','Kimmi','AFPworshipper','AFPGoddess',2);
INSERT INTO relationship VALUES (269,'sanity','cat','AFPuncle','AFPcousin',0);
INSERT INTO relationship VALUES (27,'ratty','rachel walmsley','AFPiancee','AFPiancee',2);
INSERT INTO relationship VALUES (270,'sanity','cat','AFPuncle','AFPcousin',2);
INSERT INTO relationship VALUES (271,'sanity','amy','afpbrother','afpsister',2);
INSERT INTO relationship VALUES (272,'Guitar_Huw','ryo-chan','Cuddlee','Cuddler',2);
INSERT INTO relationship VALUES (273,'Chrissy','Tiggs','AFPsis','AFPsis',1);
INSERT INTO relationship VALUES (274,'cat','rachel walmsley','AFPhiance','AFPhiance',2);
INSERT INTO relationship VALUES (275,'Marco Villalta','Orjan','vicious battle companion','vicious battle companion',2);
INSERT INTO relationship VALUES (276,'Sam','hikari','AFPhiancee','AFPhiance',2);
INSERT INTO relationship VALUES (277,'sanity','Sam','#afpNiceDad','#afpCuteDaughter',2);
INSERT INTO relationship VALUES (278,'ryo-chan','amy','#AFPsister','#Afpsister',2);
INSERT INTO relationship VALUES (279,'sanity','JamesGreen','Innocent Stepson','Evil Stepdad',2);
INSERT INTO relationship VALUES (28,'lonecat','Aquarion','worshipper','god',2);
INSERT INTO relationship VALUES (280,'JamesGreen','Melodysk','cccb suppliee','cccb supplier',2);
INSERT INTO relationship VALUES (281,'Kimmi','Rhys Smith','afpMe','afpMe',2);
INSERT INTO relationship VALUES (282,'Melodysk','Kimmi','Afpadopter','Afpadoptee',2);
INSERT INTO relationship VALUES (283,'Melodysk','lonecat','Afpadopter','Afpadoptee',2);
INSERT INTO relationship VALUES (284,'lonecat','Kimmi','Afpsister','Afpsister',2);
INSERT INTO relationship VALUES (285,'Melodysk','FiX','Afpadopter','Afpadoptee',2);
INSERT INTO relationship VALUES (286,'lonecat','FiX','Afpsister','Afpbrother',2);
INSERT INTO relationship VALUES (287,'GrumbleDook','Tiggs','AFPDarcy','AFOLizzie',1);
INSERT INTO relationship VALUES (288,'GrumbleDook','Andrea','AFPhiance','AFPhiancee',1);
INSERT INTO relationship VALUES (289,'GrumbleDook','ratty','AFPBruv','AFPsis',2);
INSERT INTO relationship VALUES (29,'nattie','rachel walmsley','Mentress','Trainee Soubrette',2);
INSERT INTO relationship VALUES (3,'sandriana','Aquarion','future sworn enemy','future sworn enemy',2);
INSERT INTO relationship VALUES (30,'nattie','Slovakia','AFPCorruptress','AFPet Sunflower Seed',2);
INSERT INTO relationship VALUES (31,'amy','nattie','AFPsecretary','AFPGuide',2);
INSERT INTO relationship VALUES (32,'Aquarion','nattie','Afphiance','Afphiancee',2);
INSERT INTO relationship VALUES (33,'Andrea','ratty','mom','bratty',2);
INSERT INTO relationship VALUES (34,'Andrea','mike','first afpiance','first afpiancee',0);
INSERT INTO relationship VALUES (35,'dragonprince','Peter','afpfance','afpfance',2);
INSERT INTO relationship VALUES (36,'Andrea','dragonprince','official unafpiancee','official unafpiance',2);
INSERT INTO relationship VALUES (37,'sandriana','dragonprince','afpfiancee','afpfiancee',2);
INSERT INTO relationship VALUES (38,'MP','Carrie Cota','afpfiance','afpfiance',2);
INSERT INTO relationship VALUES (39,'rachel walmsley','Andrea','AFPbrat','AFPmum',2);
INSERT INTO relationship VALUES (4,'Rosemary','hippo','AFPiancee','AFPfiance',2);
INSERT INTO relationship VALUES (40,'Homicide','Andrea','AFPSexslave','AFPSexslave',2);
INSERT INTO relationship VALUES (41,'Homicide','Joy','AFPBrother','AFPSister',2);
INSERT INTO relationship VALUES (42,'eric','Corinne','afpnephew','afpauntie',2);
INSERT INTO relationship VALUES (43,'eric','nattie','accompanist','backing singer',2);
INSERT INTO relationship VALUES (44,'Rhys Smith','ratty','AFPiancee','AFPiancee',2);
INSERT INTO relationship VALUES (45,'Rhys Smith','Ali W','AFPbruv','AFPsis',0);
INSERT INTO relationship VALUES (46,'SimonCallan','SusanCallan','evil twin','evil twin',2);
INSERT INTO relationship VALUES (47,'Rhys Smith','ratty','AFPbruv','AFPsis',2);
INSERT INTO relationship VALUES (48,'mmessall','eric','APFniece','AFPuncle',2);
INSERT INTO relationship VALUES (49,'mmessall','hippo','afpiancee','afpiance',2);
INSERT INTO relationship VALUES (5,'Rosemary','mike','afpiancee','afpiance',2);
INSERT INTO relationship VALUES (50,'mmessall','MP','afpiancee','afpiance',2);
INSERT INTO relationship VALUES (51,'Adrian Morgan','Laurabelle','afpbrother','afpsister',2);
INSERT INTO relationship VALUES (52,'mike','Corinne','High Priest of Procrastination','Goddess Of Procrastination',2);
INSERT INTO relationship VALUES (53,'mike','Corinne','APFiance','AFPiancee',2);
INSERT INTO relationship VALUES (54,'Peter','Joy','afpfiancé','afpfiancée',2);
INSERT INTO relationship VALUES (55,'mike','Andrea','AFPiance','first AFPiancee',2);
INSERT INTO relationship VALUES (57,'MP','Aquarion','Amazed fan','idol',2);
INSERT INTO relationship VALUES (58,'Chrissy','Homicide','AFPhiancee','AFPhiance',2);
INSERT INTO relationship VALUES (59,'Adrian Morgan','Olivia Harries','male afpsister','afpsister',2);
INSERT INTO relationship VALUES (60,'Bluebottle','dragonprince','afpsis','afpbro',2);
INSERT INTO relationship VALUES (61,'Olivia Harries','Homicide','owner','sceptula <SP?>',2);
INSERT INTO relationship VALUES (62,'Rosemary','nattie','afpiancee','afpiancee',2);
INSERT INTO relationship VALUES (63,'Aquarion','Ssirienna','afpfiancé','afpfiancée',2);
INSERT INTO relationship VALUES (64,'MartynC','mmessall','AFPhiance','AFPhiancee',2);
INSERT INTO relationship VALUES (65,'Bluebottle','Carrie Cota','#afpfiancée','#afpfiancée',2);
INSERT INTO relationship VALUES (66,'Peter','Bluebottle','bitch, oh yes he is, now please put that dow... *aaaaaaargh*','boss.',0);
INSERT INTO relationship VALUES (68,'Bluebottle','Peter','boss','bitch, oh yes he is, now please put that dow... *aaaaaaaaaaaaaaargh*',2);
INSERT INTO relationship VALUES (69,'Bluebottle','Olivia Harries','afpfiancée','afpfiancée',1);
INSERT INTO relationship VALUES (70,'Bluebottle','SusanCallan','seamstress','Mrs Palm',2);
INSERT INTO relationship VALUES (71,'Bluebottle','ccooke','alter ego','alter ego',1);
INSERT INTO relationship VALUES (72,'Peter','ccooke','French maid','chef',0);
INSERT INTO relationship VALUES (73,'Peter','mmessall','afpfiancé','afpfiancée',2);
INSERT INTO relationship VALUES (74,'Sarah','Rhys Smith','Afpiancee','Afpiance',2);
INSERT INTO relationship VALUES (75,'Sarah','mike','Afpiancee','Afpiance',2);
INSERT INTO relationship VALUES (76,'Rhys Smith','Sarah','AFPshepherd','AFPshepherdess',2);
INSERT INTO relationship VALUES (77,'Rhys Smith','Sarah','AFPfriend','AFPfriend',2);
INSERT INTO relationship VALUES (78,'hippo','Sarah','AFPfiance','AFPfiancee',2);
INSERT INTO relationship VALUES (79,'Sarah','dragonprince','afphiancee','afphiance',2);
INSERT INTO relationship VALUES (80,'Sarah','mike','bigsis','lilbro',2);
INSERT INTO relationship VALUES (81,'Melodysk','Carrie Cota','Sister','Sister',0);
INSERT INTO relationship VALUES (82,'Melodysk','dragonprince','afpfiancee','afpfiancee',0);
INSERT INTO relationship VALUES (83,'hippo','Melodysk','good influenced old fart','good influence',2);
INSERT INTO relationship VALUES (84,'Carrie Cota','dragonprince','AFPfiance','AFPfiance',2);
INSERT INTO relationship VALUES (85,'Carrie Cota','Melodysk','Evil Twin Sister','Evil Twin Sister',2);
INSERT INTO relationship VALUES (86,'Martin','Melodysk','influencee','bad influence',2);
INSERT INTO relationship VALUES (87,'Martin','Bluebottle','afpfiance','afpfiancee',2);
INSERT INTO relationship VALUES (88,'sandriana','Martin','squid','cloggie',2);
INSERT INTO relationship VALUES (89,'Rhys Smith','Melodysk','AFPYoungMan','AFPOlderWoman',2);
INSERT INTO relationship VALUES (90,'Martin','sandriana','cloggie','squid',2);
INSERT INTO relationship VALUES (91,'lonecat','dragonprince','afpfiancee','afpfiance',2);
INSERT INTO relationship VALUES (92,'lonecat','Aquarion','twin','twin',2);
INSERT INTO relationship VALUES (93,'Thomas P','mike','not-boyfriend','not-boyfriend',2);
INSERT INTO relationship VALUES (94,'Martin','Rosemary','afpfiance','afpfiancee',2);
INSERT INTO relationship VALUES (95,'dragonprince','Andrea','official unafpiancee/official unafpiance','official unafpiancee/official unafpiance',2);
INSERT INTO relationship VALUES (96,'dragonprince','Carrie Cota','afpfiancee','afpfiancee',2);
INSERT INTO relationship VALUES (97,'dragonprince','Bluebottle','afpsis/afpbro','afpsis/afpbro',0);
INSERT INTO relationship VALUES (98,'dragonprince','Sarah','afphiancee/afphiance.','afpsis/afpbroafphiancee/afphiance.',2);
INSERT INTO relationship VALUES (99,'dragonprince','Melodysk','afpfiancee.','afpfiancee',2);